export const enumPHCities = [
  "",
  "Tuguegarao City",
  "Quezon City",
  "Pasay City",
  "San Jose City",
  "Mabalacat City",
  "Batangas City",
  "Danao City",
  "Ormoc City",
  "Muñoz Science City",
  "Samal Island Garden City",
  "Caloocan City",
  "Las Piñas City",
  "Makati City",
  "Malabon City",
  "Mandaluyong City",
  "Manila City",
  "Marikina City",
  "Muntinlupa City",
  "Navotas City",
  "Parañaque City",
  "Pasig City",
  "SanJuan City",
  "Taguig City",
  "Valenzuela City",
  "Tabuk City",
  "Baguio City",
  "Batac City",
  "Laoag City",
  "Candon City",
  "Vigan City",
  "San Fernando City",
  "Alaminos City",
  "Dagupan City",
  "San Carlos City",
  "Urdaneta City",
  "Cauayan City",
  "Ilagan City",
  "Santiago City",
  "Balanga City",
  "Baliwag City",
  "Malolos City",
  "Meycauayan City",
  "San Jose Del Monte City",
  "Cabanatuan City",
  "Gapan City",
  "Palayan City",
  "San Fernando City",
  "Tarlac City",
  "Angeles City",
  "Olongapo City",
  "Calaca City",
  "Lipa City",
  "Sto.Tomas City",
  "Tanauan City",
  "Bacoor City",
  "Carmona City",
  "Cavite City",
  "Dasmariñas City",
  "General Trias City",
  "Imus City",
  "Tagaytay City",
  "Trece Martires City",
  "Biñan City",
  "Cabuyao City",
  "Calamba City",
  "San Pablo City",
  "San Pedro City",
  "Santa Rosa City",
  "Tayabas City",
  "Antipolo City",
  "Lucena City",
  "Calapan City",
  "Puerto Princesa City",
  "Legazpi City",
  "Ligao City",
  "Tabaco City",
  "Iriga City",
  "Naga City",
  "Masbate City",
  "Sorsogon City",
  "Roxas City",
  "Passi City",
  "Bago City",
  "Cadiz City",
  "Escalante City",
  "Himamaylan City",
  "Kabankalan City",
  "La Carlota City",
  "Sagay City",
  "San Carlos City",
  "Silay City",
  "Sipalay City",
  "Talisay City",
  "Victorias City",
  "Bacolod City",
  "Iloilo City",
  "Tagbilaran City",
  "Bogo City",
  "Carcar City",
  "Naga City",
  "Talisay City",
  "Toledo City",
  "Bais City",
  "Bayawan City",
  "Canlaon City",
  "Dumaguete City",
  "Guihulngan City",
  "Tanjay City",
  "Cebu City",
  "Lapu-Lapu City",
  "Mandaue City",
  "Borongan City",
  "Baybay City",
  "Calbayog City",
  "Catbalogan City",
  "Maasin City",
  "Tacloban City",
  "Dapitan City",
  "Dipolog City",
  "Pagadian City",
  "Zamboanga City",
  "Isabela City",
  "Malaybalay City",
  "Valencia City",
  "Oroquieta City",
  "Ozamiz City",
  "Tangub City",
  "El Salvador City",
  "Gingoog City",
  "Cagayan De Oro City",
  "Iligan City",
  "Panabo City",
  "Tagum City",
  "Digos City",
  "Mati City",
  "Davao City",
  "Kidapawan City",
  "Koronadal City",
  "Tacurong City",
  "General Santos City",
  "Cabadbaran City",
  "Bayugan City",
  "Surigao City",
  "Bislig City",
  "Tandag City",
  "Butuan City",
  "Lamitan City",
  "Marawi City",
  "Cotabato City",
];
